import Config

env_or = fn key, default ->
  System.get_env(key) || default
end

config :mom,
  mode: env_or.("MOM_MODE", :remote),
  llm_provider: env_or.("MOM_LLM_PROVIDER", :claude_code),
  llm_cmd: System.get_env("MOM_LLM_CMD"),
  llm_api_key: System.get_env("MOM_LLM_API_KEY"),
  llm_api_url: System.get_env("MOM_LLM_API_URL"),
  llm_model: System.get_env("MOM_LLM_MODEL"),
  github_token: System.get_env("MOM_GITHUB_TOKEN"),
  github_repo: System.get_env("MOM_GITHUB_REPO"),
  actor_id: env_or.("GITHUB_ACTOR", "mom"),
  git_ssh_command: System.get_env("MOM_GIT_SSH_COMMAND"),
  issue_rate_limit_per_hour: env_or.("MOM_ISSUE_RATE_LIMIT_PER_HOUR", 60),
  llm_rate_limit_per_hour: env_or.("MOM_LLM_RATE_LIMIT_PER_HOUR", 60),
  issue_dedupe_window_ms: env_or.("MOM_ISSUE_DEDUPE_WINDOW_MS", 3_600_000),
  poll_interval_ms: env_or.("MOM_POLL_INTERVAL_MS", 5_000),
  max_concurrency: env_or.("MOM_MAX_CONCURRENCY", 4),
  queue_max_size: env_or.("MOM_QUEUE_MAX_SIZE", 200),
  tenant_queue_max_size: System.get_env("MOM_TENANT_QUEUE_MAX_SIZE"),
  job_timeout_ms: env_or.("MOM_JOB_TIMEOUT_MS", 120_000),
  overflow_policy: env_or.("MOM_OVERFLOW_POLICY", :drop_newest),
  durable_queue_path: System.get_env("MOM_DURABLE_QUEUE_PATH"),
  temp_worktree_retention_seconds: env_or.("MOM_TEMP_WORKTREE_RETENTION_SECONDS", 86_400),
  temp_worktree_keep_latest: env_or.("MOM_TEMP_WORKTREE_KEEP_LATEST", 16),
  temp_worktree_max_active: env_or.("MOM_TEMP_WORKTREE_MAX_ACTIVE", 256),
  temp_worktree_alert_utilization_threshold:
    env_or.("MOM_TEMP_WORKTREE_ALERT_UTILIZATION_THRESHOLD", 0.75),
  execution_watchdog_enabled: env_or.("MOM_EXECUTION_WATCHDOG_ENABLED", true),
  execution_watchdog_orphan_grace_ms: env_or.("MOM_EXECUTION_WATCHDOG_ORPHAN_GRACE_MS", 250),
  audit_retention_days: env_or.("MOM_AUDIT_RETENTION_DAYS", 30),
  soc2_evidence_path: System.get_env("MOM_SOC2_EVIDENCE_PATH"),
  pii_handling_policy: env_or.("MOM_PII_HANDLING_POLICY", :redact),
  observability_backend: env_or.("MOM_OBSERVABILITY_BACKEND", :none),
  observability_export_path: System.get_env("MOM_OBSERVABILITY_EXPORT_PATH"),
  observability_export_interval_ms: env_or.("MOM_OBSERVABILITY_EXPORT_INTERVAL_MS", 5_000),
  slo_queue_depth_threshold: env_or.("MOM_SLO_QUEUE_DEPTH_THRESHOLD", 150),
  slo_drop_rate_threshold: env_or.("MOM_SLO_DROP_RATE_THRESHOLD", 0.05),
  slo_failure_rate_threshold: env_or.("MOM_SLO_FAILURE_RATE_THRESHOLD", 0.1),
  slo_latency_p95_ms_threshold: env_or.("MOM_SLO_LATENCY_P95_MS_THRESHOLD", 15_000),
  sla_triage_latency_p95_ms_target: env_or.("MOM_SLA_TRIAGE_LATENCY_P95_MS_TARGET", 15_000),
  sla_queue_durability_target: env_or.("MOM_SLA_QUEUE_DURABILITY_TARGET", 0.995),
  sla_pr_turnaround_p95_ms_target: env_or.("MOM_SLA_PR_TURNAROUND_P95_MS_TARGET", 900_000),
  error_budget_triage_latency_overage_rate:
    env_or.("MOM_ERROR_BUDGET_TRIAGE_LATENCY_OVERAGE_RATE", 0.05),
  error_budget_queue_loss_rate: env_or.("MOM_ERROR_BUDGET_QUEUE_LOSS_RATE", 0.005),
  error_budget_pr_turnaround_overage_rate:
    env_or.("MOM_ERROR_BUDGET_PR_TURNAROUND_OVERAGE_RATE", 0.1),
  llm_spend_cap_cents_per_hour: System.get_env("MOM_LLM_SPEND_CAP_CENTS_PER_HOUR"),
  llm_call_cost_cents: env_or.("MOM_LLM_CALL_COST_CENTS", 0),
  llm_token_cap_per_hour: System.get_env("MOM_LLM_TOKEN_CAP_PER_HOUR"),
  llm_tokens_per_call_estimate: env_or.("MOM_LLM_TOKENS_PER_CALL_ESTIMATE", 0),
  test_spend_cap_cents_per_hour: System.get_env("MOM_TEST_SPEND_CAP_CENTS_PER_HOUR"),
  test_run_cost_cents: env_or.("MOM_TEST_RUN_COST_CENTS", 0),
  execution_profile: env_or.("MOM_EXECUTION_PROFILE", :test_relaxed),
  test_command_profile: env_or.("MOM_TEST_COMMAND_PROFILE", :mix_test),
  open_pr: System.get_env("MOM_OPEN_PR"),
  merge_pr: env_or.("MOM_MERGE_PR", false),
  readiness_gate_approved: env_or.("MOM_READINESS_GATE_APPROVED", false),
  incident_to_pr_canary_artifact_path: System.get_env("MOM_INCIDENT_TO_PR_CANARY_ARTIFACT_PATH"),
  incident_to_pr_canary_max_age_seconds:
    env_or.("MOM_INCIDENT_TO_PR_CANARY_MAX_AGE_SECONDS", 86_400),
  branch_name_prefix: env_or.("MOM_BRANCH_NAME_PREFIX", "mom"),
  github_base_branch: env_or.("MOM_GITHUB_BASE_BRANCH", "main"),
  protected_branches: System.get_env("MOM_PROTECTED_BRANCHES"),
  allowed_github_repos: System.get_env("MOM_ALLOWED_GITHUB_REPOS"),
  allowed_actor_ids: System.get_env("MOM_ALLOWED_ACTOR_IDS"),
  allowed_egress_hosts:
    env_or.("MOM_ALLOWED_EGRESS_HOSTS", "api.github.com,api.anthropic.com,api.openai.com"),
  redact_keys:
    env_or.(
      "MOM_REDACT_KEYS",
      "password,passwd,secret,token,api_key,apikey,authorization,cookie"
    ),
  triage_on_diagnostics: env_or.("MOM_TRIAGE_ON_DIAGNOSTICS", false),
  triage_mode: env_or.("MOM_TRIAGE_MODE", :report),
  diag_run_queue_mult: env_or.("MOM_DIAG_RUN_QUEUE_MULT", 4),
  diag_mem_high_bytes: env_or.("MOM_DIAG_MEM_HIGH_BYTES", 2 * 1024 * 1024 * 1024),
  diag_cooldown_ms: env_or.("MOM_DIAG_COOLDOWN_MS", 300_000),
  min_level: env_or.("MOM_MIN_LEVEL", :error),
  dry_run: env_or.("MOM_DRY_RUN", false),
  github_credential_scopes: System.get_env("MOM_GITHUB_CREDENTIAL_SCOPES"),
  github_live_permission_verification: env_or.("MOM_GITHUB_LIVE_PERMISSION_VERIFICATION", false),
  required_node_major: env_or.("MOM_REQUIRED_NODE_MAJOR", 18),
  required_otp_version: env_or.("MOM_REQUIRED_OTP_VERSION", "28.0.2"),
  required_elixir_version: env_or.("MOM_REQUIRED_ELIXIR_VERSION", "1.19.4")

config :mom,
  defaults: [
    mode: :remote,
    llm_provider: :claude_code,
    actor_id: "mom",
    issue_rate_limit_per_hour: 60,
    llm_rate_limit_per_hour: 60,
    issue_dedupe_window_ms: 3_600_000,
    poll_interval_ms: 5_000,
    max_concurrency: 4,
    queue_max_size: 200,
    job_timeout_ms: 120_000,
    overflow_policy: :drop_newest,
    temp_worktree_retention_seconds: 86_400,
    temp_worktree_keep_latest: 16,
    temp_worktree_max_active: 256,
    temp_worktree_alert_utilization_threshold: 0.75,
    execution_watchdog_enabled: true,
    execution_watchdog_orphan_grace_ms: 250,
    audit_retention_days: 30,
    pii_handling_policy: :redact,
    observability_backend: :none,
    observability_export_interval_ms: 5_000,
    slo_queue_depth_threshold: 150,
    slo_drop_rate_threshold: 0.05,
    slo_failure_rate_threshold: 0.1,
    slo_latency_p95_ms_threshold: 15_000,
    sla_triage_latency_p95_ms_target: 15_000,
    sla_queue_durability_target: 0.995,
    sla_pr_turnaround_p95_ms_target: 900_000,
    error_budget_triage_latency_overage_rate: 0.05,
    error_budget_queue_loss_rate: 0.005,
    error_budget_pr_turnaround_overage_rate: 0.1,
    llm_call_cost_cents: 0,
    llm_tokens_per_call_estimate: 0,
    test_run_cost_cents: 0,
    execution_profile: :test_relaxed,
    test_command_profile: :mix_test,
    merge_pr: false,
    readiness_gate_approved: false,
    incident_to_pr_canary_max_age_seconds: 86_400,
    branch_name_prefix: "mom",
    github_base_branch: "main",
    allowed_egress_hosts: "api.github.com,api.anthropic.com,api.openai.com",
    redact_keys: "password,passwd,secret,token,api_key,apikey,authorization,cookie",
    triage_on_diagnostics: false,
    triage_mode: :report,
    diag_run_queue_mult: 4,
    diag_mem_high_bytes: 2 * 1024 * 1024 * 1024,
    diag_cooldown_ms: 300_000,
    min_level: :error,
    dry_run: false,
    github_live_permission_verification: false,
    required_node_major: 18,
    required_otp_version: "28.0.2",
    required_elixir_version: "1.19.4",
    governance_gates: [
      actor_identity: %Mom.Governance.Gates.Protocols.ActorIdentityGate{
        actor_id: "",
        allowed_actor_ids: [],
        github_token_present: false
      },
      repo_allowlist: %Mom.Governance.Gates.Protocols.RepoAllowlistGate{
        github_repo: nil,
        allowed_github_repos: []
      },
      readiness: %Mom.Governance.Gates.Protocols.ReadinessGate{
        enforced: false,
        open_pr: false,
        readiness_gate_approved: false,
        execution_profile: nil,
        github_base_branch: nil,
        protected_branches: nil
      },
      canary_release: %Mom.Governance.Gates.Protocols.CanaryReleaseGate{
        enforced: false,
        execution_profile: :test_relaxed,
        artifact_path: nil,
        max_age_seconds: 86_400,
        attestation_signing_key: nil
      }
    ]
  ]

config :mom,
  config2_policy_modules: [
    Mom.Governance.Policies.Runtime,
    Mom.Governance.Policies.LLM,
    Mom.Governance.Policies.Diagnostics,
    Mom.Governance.Policies.Pipeline,
    Mom.Governance.Policies.Governance,
    Mom.Governance.Policies.Compliance,
    Mom.Governance.Policies.Observability
  ],
  config2_policy_defaults: %{
    runtime: %Mom.Governance.Policies.Runtime{
      repo: "",
      node: nil,
      cookie: nil,
      mode: :remote,
      workdir: nil,
      poll_interval_ms: 5_000,
      min_level: :error,
      dry_run: false
    },
    llm: %Mom.Governance.Policies.LLM{
      execution_profile: :test_relaxed,
      provider: :claude_code,
      cmd: "codex --yolo exec"
    },
    diagnostics: %Mom.Governance.Policies.Diagnostics{
      execution_profile: :test_relaxed,
      test_command_profile: :mix_test
    },
    pipeline: %Mom.Governance.Policies.Pipeline{
      max_concurrency: 4,
      queue_max_size: 200,
      tenant_queue_max_size: nil,
      job_timeout_ms: 120_000,
      overflow_policy: :drop_newest,
      durable_queue_path: nil,
      execution_watchdog_enabled: true,
      execution_watchdog_orphan_grace_ms: 250,
      temp_worktree_max_active: 256,
      temp_worktree_alert_utilization_threshold: 0.75
    },
    governance: %Mom.Governance.Policies.Governance{
      execution_profile: :test_relaxed,
      workdir: nil,
      sandbox_mode: :unrestricted,
      command_allowlist: [],
      write_boundaries: [],
      open_pr: true,
      merge_pr: false,
      readiness_gate_approved: false
    },
    compliance: %Mom.Governance.Policies.Compliance{
      github_token: nil,
      github_repo: nil,
      github_credential_scopes: [],
      github_live_permission_verification: false,
      startup_attestation_signing_key: nil,
      open_pr: true,
      merge_pr: false
    },
    observability: %Mom.Governance.Policies.Observability{
      backend: :none,
      export_path: nil,
      export_interval_ms: 5_000,
      slo_queue_depth_threshold: 150,
      slo_drop_rate_threshold: 0.05,
      slo_failure_rate_threshold: 0.1,
      slo_latency_p95_ms_threshold: 15_000,
      sla_triage_latency_p95_ms_target: 15_000,
      sla_queue_durability_target: 0.995,
      sla_pr_turnaround_p95_ms_target: 900_000,
      error_budget_triage_latency_overage_rate: 0.05,
      error_budget_queue_loss_rate: 0.005,
      error_budget_pr_turnaround_overage_rate: 0.1
    }
  }
