defmodule Mom.GitHub do
  @moduledoc false

  alias Mom.Audit
  alias Mom.Config

  @github_api "https://api.github.com"

  @spec create_pr(Config.t(), String.t()) :: {:ok, map()} | {:error, term()}
  def create_pr(%Config{github_token: token, github_repo: repo, actor_id: actor_id}, branch) do
    with {:ok, repo} <- parse_repo(repo),
         :ok <- emit(:github_pr_attempt, %{repo: repo, actor_id: actor_id, branch: branch}),
         {:ok, body} <-
           request(
             token,
             :post,
             "/repos/#{repo}/pulls",
             %{
               "title" => "mom: fix production error",
               "head" => branch,
               "base" => "main",
               "body" => "Automated fix generated by mom."
             }
           ),
         {:ok, data} <- decode(body) do
      pr = %{url: data["html_url"], number: data["number"]}

      :ok =
        emit(:github_pr_created, %{
          repo: repo,
          actor_id: actor_id,
          branch: branch,
          pr_number: pr.number
        })

      {:ok, pr}
    else
      {:error, reason} ->
        :ok =
          emit(:github_pr_failed, %{
            repo: repo,
            actor_id: actor_id,
            branch: branch,
            reason: inspect(reason)
          })

        {:error, reason}
    end
  end

  @spec merge_pr(Config.t(), map()) :: :ok | {:error, term()}
  def merge_pr(%Config{github_token: token, github_repo: repo, actor_id: actor_id}, %{
        number: number
      }) do
    with {:ok, repo} <- parse_repo(repo),
         :ok <- emit(:github_merge_attempt, %{repo: repo, actor_id: actor_id, pr_number: number}),
         {:ok, _} <-
           request(token, :put, "/repos/#{repo}/pulls/#{number}/merge", %{
             "merge_method" => "squash"
           }) do
      :ok = emit(:github_merged, %{repo: repo, actor_id: actor_id, pr_number: number})
      :ok
    else
      {:error, reason} ->
        :ok =
          emit(:github_merge_failed, %{
            repo: repo,
            actor_id: actor_id,
            pr_number: number,
            reason: inspect(reason)
          })

        {:error, reason}
    end
  end

  @spec create_issue(Config.t(), String.t(), String.t()) :: {:ok, map()} | {:error, term()}
  def create_issue(
        %Config{github_token: token, github_repo: repo, actor_id: actor_id},
        title,
        body
      ) do
    with {:ok, repo} <- parse_repo(repo),
         :ok <- emit(:github_issue_attempt, %{repo: repo, actor_id: actor_id}),
         {:ok, resp} <-
           request(
             token,
             :post,
             "/repos/#{repo}/issues",
             %{
               "title" => title,
               "body" => body
             }
           ),
         {:ok, data} <- decode(resp) do
      issue = %{url: data["html_url"], number: data["number"]}

      :ok =
        emit(:github_issue_created, %{repo: repo, actor_id: actor_id, issue_number: issue.number})

      {:ok, issue}
    else
      {:error, reason} ->
        :ok =
          emit(:github_issue_failed, %{repo: repo, actor_id: actor_id, reason: inspect(reason)})

        {:error, reason}
    end
  end

  defp request(token, method, path, payload) do
    headers = [
      {~c"authorization", ~c"Bearer " ++ to_charlist(token)},
      {~c"user-agent", ~c"mom"},
      {~c"accept", ~c"application/vnd.github+json"}
    ]

    body = Jason.encode!(payload)
    url = String.to_charlist(@github_api <> path)

    case http_client().request(method, {url, headers, ~c"application/json", body}, [], []) do
      {:ok, {{_, status, _}, _headers, resp}} when status in 200..299 -> {:ok, resp}
      {:ok, {{_, status, _}, _headers, resp}} -> {:error, {:http_error, status, resp}}
      {:error, reason} -> {:error, reason}
    end
  end

  defp decode(body) do
    case Jason.decode(body) do
      {:ok, data} -> {:ok, data}
      {:error, reason} -> {:error, reason}
    end
  end

  defp parse_repo(nil), do: {:error, "github_repo is required"}

  defp parse_repo(repo) do
    case String.split(repo, "/") do
      [owner, name] -> {:ok, "#{owner}/#{name}"}
      _ -> {:error, "github_repo must be in owner/name format"}
    end
  end

  defp emit(event, metadata) do
    Audit.emit(event, metadata)
  end

  defp http_client do
    Application.get_env(:mom, :github_http_client, Mom.GitHub.HttpClient)
  end
end

defmodule Mom.GitHub.HttpClient do
  @moduledoc false

  def request(method, request, http_options, options) do
    :inets.start()
    :ssl.start()
    :httpc.request(method, request, http_options, options)
  end
end
