defmodule Mom.GitHub do
  @moduledoc false

  alias Mom.Config

  @github_api "https://api.github.com"

  @spec create_pr(Config.t(), String.t()) :: {:ok, map()} | {:error, term()}
  def create_pr(%Config{github_token: token, github_repo: repo}, branch) do
    with {:ok, repo} <- parse_repo(repo),
         {:ok, body} <-
           request(
             token,
             :post,
             "/repos/#{repo}/pulls",
             %{
               "title" => "mom: fix production error",
               "head" => branch,
               "base" => "main",
               "body" => "Automated fix generated by mom."
             }
           ),
         {:ok, data} <- decode(body) do
      {:ok, %{url: data["html_url"], number: data["number"]}}
    end
  end

  @spec merge_pr(Config.t(), map()) :: :ok | {:error, term()}
  def merge_pr(%Config{github_token: token, github_repo: repo}, %{number: number}) do
    with {:ok, repo} <- parse_repo(repo),
         {:ok, _} <-
           request(token, :put, "/repos/#{repo}/pulls/#{number}/merge", %{
             "merge_method" => "squash"
           }) do
      :ok
    end
  end

  @spec create_issue(Config.t(), String.t(), String.t()) :: {:ok, map()} | {:error, term()}
  def create_issue(%Config{github_token: token, github_repo: repo}, title, body) do
    with {:ok, repo} <- parse_repo(repo),
         {:ok, resp} <-
           request(
             token,
             :post,
             "/repos/#{repo}/issues",
             %{
               "title" => title,
               "body" => body
             }
           ),
         {:ok, data} <- decode(resp) do
      {:ok, %{url: data["html_url"], number: data["number"]}}
    end
  end

  defp request(token, method, path, payload) do
    headers = [
      {~c"authorization", ~c"Bearer " ++ to_charlist(token)},
      {~c"user-agent", ~c"mom"},
      {~c"accept", ~c"application/vnd.github+json"}
    ]

    body = Jason.encode!(payload)
    url = String.to_charlist(@github_api <> path)

    :inets.start()
    :ssl.start()

    case :httpc.request(method, {url, headers, ~c"application/json", body}, [], []) do
      {:ok, {{_, status, _}, _headers, resp}} when status in 200..299 -> {:ok, resp}
      {:ok, {{_, status, _}, _headers, resp}} -> {:error, {:http_error, status, resp}}
      {:error, reason} -> {:error, reason}
    end
  end

  defp decode(body) do
    case Jason.decode(body) do
      {:ok, data} -> {:ok, data}
      {:error, reason} -> {:error, reason}
    end
  end

  defp parse_repo(nil), do: {:error, "github_repo is required"}

  defp parse_repo(repo) do
    case String.split(repo, "/") do
      [owner, name] -> {:ok, "#{owner}/#{name}"}
      _ -> {:error, "github_repo must be in owner/name format"}
    end
  end
end
